-- Creator Messages table
-- Individual messages within conversations

-- Message sender type enum
DO $$ BEGIN
  CREATE TYPE message_sender_type AS ENUM ('creator', 'admin');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Message status enum
DO $$ BEGIN
  CREATE TYPE message_status AS ENUM ('sent', 'delivered', 'read');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS creator_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Conversation reference
  conversation_id UUID NOT NULL REFERENCES creator_conversations(id) ON DELETE CASCADE,

  -- Message content
  content TEXT NOT NULL,

  -- Sender information
  sender_type message_sender_type NOT NULL,
  sender_id UUID,        -- creator_id or admin user_id
  sender_name TEXT,      -- Display name of sender

  -- Message state
  status message_status NOT NULL DEFAULT 'sent',
  read_at TIMESTAMPTZ,

  -- Metadata
  ai_generated BOOLEAN NOT NULL DEFAULT FALSE,  -- If message was AI-generated
  reply_to_id UUID REFERENCES creator_messages(id) ON DELETE SET NULL,

  -- Attachments (stored as JSON array of URLs)
  attachments JSONB DEFAULT '[]'::jsonb,

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Trigger for updated_at
DROP TRIGGER IF EXISTS update_creator_messages_updated_at ON creator_messages;
CREATE TRIGGER update_creator_messages_updated_at
  BEFORE UPDATE ON creator_messages
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_creator_messages_conversation_id ON creator_messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_creator_messages_created_at ON creator_messages(conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_creator_messages_sender ON creator_messages(sender_type, sender_id);

-- Function to update conversation on new message
CREATE OR REPLACE FUNCTION update_conversation_on_message()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE creator_conversations
  SET
    last_message_at = NEW.created_at,
    last_message_preview = LEFT(NEW.content, 100),
    last_message_sender = NEW.sender_type::TEXT,
    unread_creator = CASE WHEN NEW.sender_type = 'admin' THEN unread_creator + 1 ELSE unread_creator END,
    unread_admin = CASE WHEN NEW.sender_type = 'creator' THEN unread_admin + 1 ELSE unread_admin END,
    updated_at = NOW()
  WHERE id = NEW.conversation_id;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update conversation on new message
DROP TRIGGER IF EXISTS trigger_update_conversation_on_message ON creator_messages;
CREATE TRIGGER trigger_update_conversation_on_message
  AFTER INSERT ON creator_messages
  FOR EACH ROW
  EXECUTE FUNCTION update_conversation_on_message();

COMMENT ON TABLE creator_messages IS 'Individual messages within creator conversations.';
COMMENT ON COLUMN creator_messages.ai_generated IS 'True if message was generated by AI assistant.';
COMMENT ON COLUMN creator_messages.attachments IS 'JSON array of attachment URLs.';
