import {
  LayoutDashboard,
  FileText,
  ShoppingCart,
  BarChart3,
  Users,
  HardHat,
  Wallet,
  Activity,
  Settings,
  Calendar,
  Bot,
  Mail,
  Headphones,
  ClipboardList,
  FileSignature,
  Plug,
  UserCircle,
  Gift,
  GitBranch,
  Film,
  Image,
  Users2,
  Settings2,
  MessageSquare,
  Briefcase,
  TrendingUp,
  FolderKanban,
  ImageIcon,
  Rss,
  Phone,
  type LucideIcon,
} from 'lucide-react'

export interface NavChild {
  label: string
  href: string
}

export interface NavSection {
  label: string
  icon: LucideIcon
  href: string
  children?: NavChild[]
  featureFlag?: string
}

export const navigation: NavSection[] = [
  {
    label: 'Dashboard',
    icon: LayoutDashboard,
    href: '/admin',
  },
  {
    label: 'Blog',
    icon: FileText,
    href: '/admin/blog',
    children: [
      { label: 'All Posts', href: '/admin/blog' },
      { label: 'New Post', href: '/admin/blog/new' },
      { label: 'Categories', href: '/admin/blog/categories' },
      { label: 'Authors', href: '/admin/blog/authors' },
    ],
  },
  {
    label: 'Landing Pages',
    icon: FileText,
    href: '/admin/landing-pages',
    children: [
      { label: 'All Pages', href: '/admin/landing-pages' },
      { label: 'New Page', href: '/admin/landing-pages/new' },
    ],
  },
  {
    label: 'Brand Context',
    icon: Briefcase,
    href: '/admin/brand-context',
    children: [
      { label: 'Overview', href: '/admin/brand-context' },
      { label: 'New Context', href: '/admin/brand-context/new' },
    ],
  },
  {
    label: 'SEO',
    icon: BarChart3,
    href: '/admin/seo',
    children: [
      { label: 'Overview', href: '/admin/seo' },
      { label: 'Keywords', href: '/admin/seo/keywords' },
      { label: 'Analysis', href: '/admin/seo/analysis' },
      { label: 'Content Gap', href: '/admin/seo/content-gap' },
      { label: 'Redirects', href: '/admin/seo/redirects' },
      { label: 'Schema', href: '/admin/seo/schema' },
      { label: 'Settings', href: '/admin/seo/settings' },
    ],
  },
  {
    label: 'Commerce',
    icon: ShoppingCart,
    href: '/admin/commerce',
    children: [
      { label: 'Orders', href: '/admin/commerce/orders' },
      { label: 'Customers', href: '/admin/commerce/customers' },
      { label: 'Subscriptions', href: '/admin/commerce/subscriptions' },
      { label: 'Selling Plans', href: '/admin/commerce/selling-plans' },
      { label: 'Reviews', href: '/admin/commerce/reviews' },
      { label: 'A/B Tests', href: '/admin/ab-tests' },
      { label: 'Promotions', href: '/admin/commerce/promotions' },
      { label: 'Promo Codes', href: '/admin/commerce/promo-codes' },
      { label: 'Abandoned Checkouts', href: '/admin/commerce/abandoned-checkouts' },
      { label: 'Samples Orders', href: '/admin/commerce/samples-orders' },
    ],
  },
  {
    label: 'Gift Cards',
    icon: Gift,
    href: '/admin/gift-cards',
    children: [
      { label: 'Dashboard', href: '/admin/gift-cards' },
      { label: 'Products', href: '/admin/gift-cards/products' },
      { label: 'Transactions', href: '/admin/gift-cards/transactions' },
      { label: 'Emails', href: '/admin/gift-cards/emails' },
      { label: 'Settings', href: '/admin/gift-cards/settings' },
    ],
  },
  {
    label: 'Customer Portal',
    icon: UserCircle,
    href: '/admin/customer-portal',
  },
  {
    label: 'Media',
    icon: Film,
    href: '/admin/videos',
    children: [
      { label: 'Video Library', href: '/admin/videos' },
      { label: 'UGC Gallery', href: '/admin/gallery' },
      { label: 'Recorder', href: '/admin/recorder' },
    ],
  },
  {
    label: 'DAM',
    icon: ImageIcon,
    href: '/admin/dam',
    children: [
      { label: 'Assets', href: '/admin/dam' },
      { label: 'Upload', href: '/admin/dam/upload' },
    ],
  },
  {
    label: 'Samples',
    icon: Image,
    href: '/admin/samples',
    children: [
      { label: 'Overview', href: '/admin/samples' },
      { label: 'New Request', href: '/admin/samples/new' },
    ],
  },
  {
    label: 'Surveys',
    icon: ClipboardList,
    href: '/admin/surveys',
    children: [
      { label: 'All Surveys', href: '/admin/surveys' },
      { label: 'New Survey', href: '/admin/surveys/new' },
      { label: 'Attribution Options', href: '/admin/surveys/attribution' },
      { label: 'Slack Integration', href: '/admin/surveys/slack' },
    ],
  },
  {
    label: 'Attribution',
    icon: BarChart3,
    href: '/admin/attribution',
    featureFlag: 'attribution',
    children: [
      { label: 'Overview', href: '/admin/attribution' },
      { label: 'Channels', href: '/admin/attribution/channels' },
      { label: 'Journeys', href: '/admin/attribution/journeys' },
      { label: 'AI Insights', href: '/admin/attribution/ai-insights' },
      { label: 'Creatives', href: '/admin/attribution/creatives' },
      { label: 'Cohorts', href: '/admin/attribution/cohorts' },
      { label: 'Influencers', href: '/admin/attribution/influencers' },
      { label: 'Products', href: '/admin/attribution/products' },
      { label: 'Platforms', href: '/admin/attribution/platforms' },
      { label: 'MMM', href: '/admin/attribution/mmm' },
      { label: 'ROAS Index', href: '/admin/attribution/roas-index' },
      { label: 'Incrementality', href: '/admin/attribution/incrementality' },
      { label: 'Model Comparison', href: '/admin/attribution/model-comparison' },
      { label: 'Data Quality', href: '/admin/attribution/data-quality' },
      { label: 'Pixels', href: '/admin/attribution/pixels' },
      { label: 'Dashboards', href: '/admin/attribution/dashboards' },
      { label: 'Reports', href: '/admin/attribution/reports' },
      { label: 'Exports', href: '/admin/attribution/exports' },
      { label: 'Setup', href: '/admin/attribution/setup' },
      { label: 'Settings', href: '/admin/attribution/settings' },
    ],
  },
  {
    label: 'Analytics',
    icon: TrendingUp,
    href: '/admin/analytics',
    children: [
      { label: 'Dashboard', href: '/admin/analytics' },
      { label: 'BRI', href: '/admin/analytics/bri' },
      { label: 'Pipeline', href: '/admin/analytics/pipeline' },
      { label: 'P&L Breakdown', href: '/admin/analytics/pl-breakdown' },
      { label: 'Reports', href: '/admin/analytics/reports' },
      { label: 'Settings', href: '/admin/analytics/settings' },
    ],
  },
  {
    label: 'Segments',
    icon: FolderKanban,
    href: '/admin/segments',
    children: [
      { label: 'All Segments', href: '/admin/segments' },
    ],
  },
  {
    label: 'Creators',
    icon: Users,
    href: '/admin/creators',
    featureFlag: 'creators',
    children: [
      { label: 'Directory', href: '/admin/creators' },
      { label: 'Applications', href: '/admin/creators/applications' },
      { label: 'Pipeline', href: '/admin/creator-pipeline' },
      { label: 'Analytics', href: '/admin/creators/analytics' },
      { label: 'Inbox', href: '/admin/creators/inbox' },
      { label: 'Communications', href: '/admin/creators/communications' },
      { label: 'Onboarding Settings', href: '/admin/creators/onboarding-settings' },
    ],
  },
  {
    label: 'Contractors',
    icon: HardHat,
    href: '/admin/contractors',
    featureFlag: 'contractors',
    children: [
      { label: 'Directory', href: '/admin/contractors' },
      { label: 'Invite', href: '/admin/contractors/invite' },
    ],
  },
  {
    label: 'E-Signatures',
    icon: FileSignature,
    href: '/admin/esign',
    featureFlag: 'esign',
    children: [
      { label: 'Dashboard', href: '/admin/esign' },
      { label: 'Documents', href: '/admin/esign/documents' },
      { label: 'Pending', href: '/admin/esign/pending' },
      { label: 'Counter-Sign', href: '/admin/esign/counter-sign' },
      { label: 'Templates', href: '/admin/esign/templates' },
      { label: 'Bulk Send', href: '/admin/esign/bulk-send' },
      { label: 'Reports', href: '/admin/esign/reports' },
      { label: 'Webhooks', href: '/admin/esign/webhooks' },
    ],
  },
  {
    label: 'Scheduling',
    icon: Calendar,
    href: '/admin/scheduling',
    featureFlag: 'scheduling',
    children: [
      { label: 'Dashboard', href: '/admin/scheduling' },
      { label: 'Event Types', href: '/admin/scheduling/event-types' },
      { label: 'Availability', href: '/admin/scheduling/availability' },
      { label: 'Bookings', href: '/admin/scheduling/bookings' },
      { label: 'Analytics', href: '/admin/scheduling/analytics' },
      { label: 'Settings', href: '/admin/scheduling/settings' },
    ],
  },
  {
    label: 'Support',
    icon: Headphones,
    href: '/admin/support',
    children: [
      { label: 'Dashboard', href: '/admin/support' },
      { label: 'Tickets', href: '/admin/support/tickets' },
      { label: 'Agents', href: '/admin/support/agents' },
      { label: 'Chat', href: '/admin/support/chat' },
      { label: 'CSAT', href: '/admin/support/csat' },
      { label: 'Privacy', href: '/admin/support/privacy' },
      { label: 'Settings', href: '/admin/support/settings' },
    ],
  },
  {
    label: 'Inbox',
    icon: MessageSquare,
    href: '/admin/inbox',
    children: [
      { label: 'Messages', href: '/admin/inbox' },
      { label: 'Contacts', href: '/admin/inbox/contacts' },
    ],
  },
  {
    label: 'Finance',
    icon: Wallet,
    href: '/admin/payouts',
    children: [
      { label: 'Payouts', href: '/admin/payouts' },
      { label: 'Treasury', href: '/admin/treasury' },
      { label: 'Stripe Top-ups', href: '/admin/stripe-topups' },
      { label: 'Expenses', href: '/admin/expenses' },
      { label: 'Commissions', href: '/admin/commissions' },
      { label: 'Tax / 1099', href: '/admin/tax' },
    ],
  },
  {
    label: 'Team',
    icon: Users2,
    href: '/admin/team',
    children: [
      { label: 'Members', href: '/admin/settings/team' },
      { label: 'Roles', href: '/admin/team/roles' },
    ],
  },
  {
    label: 'Bri',
    icon: Bot,
    href: '/admin/bri',
    featureFlag: 'aiAgents',
    children: [
      { label: 'Dashboard', href: '/admin/bri' },
      { label: 'Conversations', href: '/admin/bri/conversations' },
      { label: 'Action Log', href: '/admin/bri/action-log' },
      { label: 'Creative Ideas', href: '/admin/bri/creative-ideas' },
      { label: 'Autonomy', href: '/admin/bri/autonomy' },
      { label: 'Voice', href: '/admin/bri/voice' },
      { label: 'Voice Calls', href: '/admin/ai-team/calls' },
      { label: 'Integrations', href: '/admin/bri/integrations' },
      { label: 'Team Memories', href: '/admin/bri/team-memories' },
      { label: 'Team Defaults', href: '/admin/bri/team-defaults' },
      { label: 'Slack Users', href: '/admin/bri/slack-users' },
      { label: 'Notifications', href: '/admin/bri/notifications' },
      { label: 'Follow-ups', href: '/admin/bri/followups' },
    ],
  },
  {
    label: 'Templates',
    icon: Mail,
    href: '/admin/templates',
    children: [
      { label: 'Library', href: '/admin/templates' },
      { label: 'Analytics', href: '/admin/templates/analytics' },
    ],
  },
  {
    label: 'Operations',
    icon: Activity,
    href: '/admin/operations',
    children: [
      { label: 'Dashboard', href: '/admin/operations' },
      { label: 'Logs', href: '/admin/operations/logs' },
      { label: 'Errors', href: '/admin/operations/errors' },
      { label: 'Health', href: '/admin/operations/health' },
    ],
  },
  {
    label: 'Workflows',
    icon: GitBranch,
    href: '/admin/workflows',
    children: [
      { label: 'Dashboard', href: '/admin/workflows' },
      { label: 'Create New', href: '/admin/workflows/new' },
      { label: 'Approvals', href: '/admin/workflows/approvals' },
      { label: 'Logs', href: '/admin/workflows/logs' },
      { label: 'Scheduled', href: '/admin/workflows/scheduled' },
    ],
  },
  {
    label: 'Integrations',
    icon: Plug,
    href: '/admin/integrations',
    children: [
      { label: 'Overview', href: '/admin/integrations' },
      { label: 'Shopify', href: '/admin/integrations/shopify-app' },
      { label: 'Meta Ads', href: '/admin/integrations/meta-ads' },
      { label: 'Google Ads', href: '/admin/integrations/google-ads' },
      { label: 'TikTok Ads', href: '/admin/integrations/tiktok-ads' },
      { label: 'SMS & Voice', href: '/admin/integrations/sms' },
      { label: 'Slack', href: '/admin/integrations/slack' },
      { label: 'Klaviyo', href: '/admin/integrations/klaviyo' },
      { label: 'Yotpo', href: '/admin/integrations/yotpo' },
      { label: 'MCP', href: '/admin/integrations/mcp' },
    ],
  },
  {
    label: 'Google Feed',
    icon: Rss,
    href: '/admin/google-feed',
    children: [
      { label: 'Overview', href: '/admin/google-feed' },
      { label: 'Products', href: '/admin/google-feed/products' },
      { label: 'Images', href: '/admin/google-feed/images' },
      { label: 'Preview', href: '/admin/google-feed/preview' },
      { label: 'Settings', href: '/admin/google-feed/settings' },
    ],
  },
  {
    label: 'System',
    icon: Settings2,
    href: '/admin/system',
    children: [
      { label: 'Sync', href: '/admin/system/sync' },
      { label: 'Config', href: '/admin/config' },
      { label: 'Changelog', href: '/admin/changelog' },
      { label: 'Onboarding Metrics', href: '/admin/onboarding-metrics' },
    ],
  },
  {
    label: 'Settings',
    icon: Settings,
    href: '/admin/settings',
    children: [
      { label: 'General', href: '/admin/settings/general' },
      { label: 'Domains', href: '/admin/settings/domains' },
      { label: 'Shopify', href: '/admin/settings/shopify' },
      { label: 'Payments', href: '/admin/settings/payments' },
      { label: 'Payouts', href: '/admin/settings/payouts' },
      { label: 'Costs', href: '/admin/settings/costs' },
      { label: 'Portal', href: '/admin/settings/portal' },
      { label: 'AI', href: '/admin/settings/ai' },
      { label: 'Email', href: '/admin/settings/email' },
      { label: 'Permissions', href: '/admin/settings/permissions' },
      { label: 'Integrations', href: '/admin/settings/integrations' },
      { label: 'Credentials', href: '/admin/settings/integrations/credentials' },
    ],
  },
]
