import { writeFileSync } from 'fs'
import { join } from 'path'
import ora from 'ora'

/**
 * Wizard answers collected from user
 */
export interface WizardAnswers {
  useCase: string
  commerceProvider: 'shopify' | 'custom'
  storefrontType: 'headless-react' | 'shopify-liquid'
  checkoutProvider: 'shopify' | 'stripe'
  cacheProducts: boolean
  multiTenant: boolean
}

/**
 * Validation result
 */
export interface ValidationResult {
  valid: boolean
  warnings: string[]
}

/**
 * Generate platform.config.ts from wizard answers
 */
export async function generatePlatformConfig(answers: WizardAnswers): Promise<void> {
  const spinner = ora('Generating platform.config.ts...').start()

  try {
    const config = `import { type PlatformConfig } from '@cgk-platform/core'

/**
 * CGK Platform Configuration
 * Generated by: npx @cgk-platform/cli wizard
 * Use case: ${answers.useCase}
 */
export const platformConfig: PlatformConfig = {
  // Use case configuration
  useCase: '${answers.useCase}',

  // Commerce provider
  commerce: {
    provider: '${answers.commerceProvider}',
    shopify: ${
      answers.commerceProvider === 'shopify'
        ? `{
      enabled: true,
      storefrontType: '${answers.storefrontType}',
      checkout: '${answers.checkoutProvider}',
      cacheProducts: ${answers.cacheProducts},
    }`
        : `{
      enabled: false,
    }`
    },
    stripe: ${
      answers.checkoutProvider === 'stripe' || answers.commerceProvider === 'custom'
        ? `{
      enabled: true,
      mode: 'payment',
    }`
        : `{
      enabled: false,
    }`
    },
  },

  // Storefront configuration
  storefront: {
    type: '${answers.storefrontType}',
    caching: {
      enabled: ${answers.cacheProducts},
      ttl: 300, // 5 minutes
    },
  },

  // Multi-tenancy
  multiTenant: {
    enabled: ${answers.multiTenant},
    isolation: 'schema-per-tenant',
  },

  // Features
  features: {
    creatorPortal: ${answers.useCase === 'creator' || answers.useCase === 'marketplace'},
    contractorPortal: ${answers.useCase === 'b2b' || answers.useCase === 'marketplace'},
    subscriptions: ${answers.useCase === 'creator'},
    wholesale: ${answers.useCase === 'b2b'},
  },
}

export default platformConfig
`

    const configPath = join(process.cwd(), 'platform.config.ts')
    writeFileSync(configPath, config)

    spinner.succeed('platform.config.ts created')
  } catch (error) {
    spinner.fail('Failed to create platform.config.ts')
    throw error
  }
}

/**
 * Update database settings table with wizard answers
 */
export async function updateDatabaseSettings(answers: WizardAnswers): Promise<void> {
  const spinner = ora('Updating database settings...').start()

  try {
    // Dynamic import to avoid loading db package if not installed
    const { sql } = await import('@vercel/postgres')

    const settings = {
      platform_use_case: answers.useCase,
      commerce_provider: answers.commerceProvider,
      storefront_type: answers.storefrontType,
      checkout_provider: answers.checkoutProvider,
      cache_products: answers.cacheProducts.toString(),
      multi_tenant_enabled: answers.multiTenant.toString(),
    }

    for (const [key, value] of Object.entries(settings)) {
      await sql`
        INSERT INTO public.settings (key, value, created_at, updated_at)
        VALUES (${key}, ${value}, NOW(), NOW())
        ON CONFLICT (key)
        DO UPDATE SET
          value = EXCLUDED.value,
          updated_at = NOW()
      `
    }

    spinner.succeed('Database settings updated')
  } catch (error) {
    spinner.warn('Database settings update skipped (database not available)')
    // Don't throw - database might not be set up yet
  }
}

/**
 * Validate wizard configuration for potential conflicts
 */
export function validateConfig(answers: WizardAnswers): ValidationResult {
  const warnings: string[] = []

  // Check for incompatible combinations
  if (answers.storefrontType === 'shopify-liquid' && answers.checkoutProvider === 'stripe') {
    warnings.push(
      'Shopify Liquid storefronts typically use Shopify checkout. ' +
        'Using Stripe checkout may require significant customization.'
    )
  }

  if (
    answers.commerceProvider === 'custom' &&
    answers.checkoutProvider === 'shopify' &&
    answers.storefrontType !== 'shopify-liquid'
  ) {
    warnings.push(
      'Custom commerce provider with Shopify checkout is unusual. ' +
        'Consider using Stripe checkout instead.'
    )
  }

  if (answers.multiTenant && answers.storefrontType === 'shopify-liquid') {
    warnings.push(
      'Multi-tenant with Shopify Liquid themes requires careful theme isolation. ' +
        'Headless React is recommended for multi-tenant setups.'
    )
  }

  if (!answers.cacheProducts && answers.commerceProvider === 'shopify') {
    warnings.push(
      'Disabling product caching with Shopify may result in slower page loads. ' +
        'Consider enabling caching for better performance.'
    )
  }

  return {
    valid: warnings.length === 0,
    warnings,
  }
}
