/**
 * PDF generator for treasury draw requests
 *
 * Generates professional PDF documents for treasurer approval
 */

import type { DrawRequestWithItems } from './types'

/**
 * PDF generation options
 */
export interface PdfGeneratorOptions {
  companyName?: string
  companyLogo?: string
  companyAddress?: string
  footerText?: string
}

/**
 * Generate PDF content as a data structure
 * This can be used with various PDF libraries or services
 */
export function generatePdfContent(
  request: DrawRequestWithItems,
  options: PdfGeneratorOptions = {}
): PdfDocument {
  const {
    companyName = 'CGK Platform',
    companyAddress = '',
    footerText = 'Generated by CGK Treasury Management',
  } = options

  const formattedDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  const dueDate = request.due_date
    ? new Date(request.due_date).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      })
    : 'Not specified'

  return {
    title: `Draw Request ${request.request_number}`,
    header: {
      companyName,
      companyAddress,
      documentTitle: 'DRAW REQUEST',
      requestNumber: request.request_number,
      date: formattedDate,
    },
    summary: {
      description: request.description,
      totalAmount: formatCurrency(request.total_amount_cents),
      dueDate,
      treasurerName: request.treasurer_name,
      treasurerEmail: request.treasurer_email,
    },
    lineItems: request.items.map((item, index) => ({
      number: index + 1,
      payee: item.creator_name,
      description: item.project_description || '-',
      amount: formatCurrency(item.net_amount_cents),
    })),
    totals: {
      subtotal: formatCurrency(request.total_amount_cents),
      total: formatCurrency(request.total_amount_cents),
    },
    signatures: request.signers.map((signer) => ({
      name: signer,
      line: '_'.repeat(40),
      dateLabel: 'Date: _____________',
    })),
    footer: {
      text: footerText,
      generatedAt: new Date().toISOString(),
    },
  }
}

/**
 * PDF document structure
 */
export interface PdfDocument {
  title: string
  header: {
    companyName: string
    companyAddress: string
    documentTitle: string
    requestNumber: string
    date: string
  }
  summary: {
    description: string
    totalAmount: string
    dueDate: string
    treasurerName: string
    treasurerEmail: string
  }
  lineItems: {
    number: number
    payee: string
    description: string
    amount: string
  }[]
  totals: {
    subtotal: string
    total: string
  }
  signatures: {
    name: string
    line: string
    dateLabel: string
  }[]
  footer: {
    text: string
    generatedAt: string
  }
}

/**
 * Generate PDF using an external service (placeholder)
 * In production, implement with your preferred PDF service
 */
export async function generatePdf(
  request: DrawRequestWithItems,
  options: PdfGeneratorOptions = {}
): Promise<{ success: boolean; url?: string; buffer?: Buffer; error?: string }> {
  const content = generatePdfContent(request, options)

  // Try to use a PDF generation service
  const pdfApiKey = process.env.PDF_API_KEY
  const pdfApiUrl = process.env.PDF_API_URL

  if (pdfApiKey && pdfApiUrl) {
    try {
      const response = await fetch(pdfApiUrl, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${pdfApiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          template: 'draw-request',
          data: content,
        }),
      })

      if (response.ok) {
        const data = await response.json()
        return { success: true, url: data.url }
      }
    } catch (error) {
      console.error('PDF API error:', error)
    }
  }

  // Fallback: Generate simple HTML that can be converted to PDF
  const html = generateHtmlDocument(content)

  return {
    success: true,
    buffer: Buffer.from(html),
  }
}

/**
 * Generate HTML document that can be printed as PDF
 */
export function generateHtmlDocument(content: PdfDocument): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${content.title}</title>
  <style>
    @page {
      size: A4;
      margin: 20mm;
    }

    body {
      font-family: 'Helvetica Neue', Arial, sans-serif;
      font-size: 12px;
      line-height: 1.5;
      color: #333;
      max-width: 210mm;
      margin: 0 auto;
      padding: 20px;
    }

    .header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      border-bottom: 2px solid #1e40af;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }

    .company-info {
      text-align: left;
    }

    .company-name {
      font-size: 24px;
      font-weight: bold;
      color: #1e40af;
      margin-bottom: 4px;
    }

    .company-address {
      color: #666;
      font-size: 11px;
    }

    .document-info {
      text-align: right;
    }

    .document-title {
      font-size: 20px;
      font-weight: bold;
      color: #1e40af;
    }

    .request-number {
      font-size: 14px;
      color: #666;
      margin-top: 4px;
    }

    .date {
      font-size: 12px;
      color: #666;
    }

    .summary {
      background: #f8fafc;
      padding: 20px;
      border-radius: 8px;
      margin-bottom: 30px;
    }

    .summary h2 {
      margin: 0 0 15px;
      font-size: 14px;
      color: #1e40af;
      text-transform: uppercase;
    }

    .summary-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 10px;
    }

    .summary-item {
      margin-bottom: 10px;
    }

    .summary-label {
      font-size: 11px;
      color: #666;
      text-transform: uppercase;
    }

    .summary-value {
      font-size: 14px;
      font-weight: 500;
    }

    .summary-value.amount {
      font-size: 24px;
      color: #1e40af;
      font-weight: bold;
    }

    .line-items {
      margin-bottom: 30px;
    }

    .line-items h2 {
      font-size: 14px;
      color: #1e40af;
      text-transform: uppercase;
      margin-bottom: 15px;
    }

    table {
      width: 100%;
      border-collapse: collapse;
    }

    th, td {
      padding: 12px;
      text-align: left;
      border-bottom: 1px solid #e2e8f0;
    }

    th {
      background: #1e40af;
      color: white;
      font-weight: 500;
      text-transform: uppercase;
      font-size: 11px;
    }

    td.amount {
      text-align: right;
      font-family: 'Monaco', 'Consolas', monospace;
    }

    th.amount {
      text-align: right;
    }

    tr:nth-child(even) {
      background: #f8fafc;
    }

    .totals {
      display: flex;
      justify-content: flex-end;
      margin-bottom: 40px;
    }

    .totals-table {
      width: 250px;
    }

    .totals-table td {
      padding: 8px 12px;
    }

    .totals-table .total-row {
      font-weight: bold;
      font-size: 16px;
      background: #1e40af;
      color: white;
    }

    .signatures {
      margin-top: 40px;
      page-break-inside: avoid;
    }

    .signatures h2 {
      font-size: 14px;
      color: #1e40af;
      text-transform: uppercase;
      margin-bottom: 30px;
    }

    .signature-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 40px;
    }

    .signature-block {
      border-top: 2px solid #333;
      padding-top: 10px;
    }

    .signature-name {
      font-weight: 500;
    }

    .signature-date {
      color: #666;
      font-size: 11px;
      margin-top: 5px;
    }

    .footer {
      position: fixed;
      bottom: 0;
      left: 0;
      right: 0;
      padding: 20px;
      text-align: center;
      font-size: 10px;
      color: #666;
      border-top: 1px solid #e2e8f0;
    }

    @media print {
      body {
        padding: 0;
      }
      .footer {
        position: fixed;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="company-info">
      <div class="company-name">${content.header.companyName}</div>
      ${content.header.companyAddress ? `<div class="company-address">${content.header.companyAddress}</div>` : ''}
    </div>
    <div class="document-info">
      <div class="document-title">${content.header.documentTitle}</div>
      <div class="request-number">${content.header.requestNumber}</div>
      <div class="date">${content.header.date}</div>
    </div>
  </div>

  <div class="summary">
    <h2>Request Summary</h2>
    <div class="summary-grid">
      <div class="summary-item">
        <div class="summary-label">Description</div>
        <div class="summary-value">${content.summary.description}</div>
      </div>
      <div class="summary-item">
        <div class="summary-label">Total Amount</div>
        <div class="summary-value amount">${content.summary.totalAmount}</div>
      </div>
      <div class="summary-item">
        <div class="summary-label">Due Date</div>
        <div class="summary-value">${content.summary.dueDate}</div>
      </div>
      <div class="summary-item">
        <div class="summary-label">Treasurer</div>
        <div class="summary-value">${content.summary.treasurerName}</div>
        <div class="summary-label" style="margin-top: 2px;">${content.summary.treasurerEmail}</div>
      </div>
    </div>
  </div>

  <div class="line-items">
    <h2>Line Items</h2>
    <table>
      <thead>
        <tr>
          <th style="width: 50px;">#</th>
          <th>Payee</th>
          <th>Description</th>
          <th class="amount" style="width: 120px;">Amount</th>
        </tr>
      </thead>
      <tbody>
        ${content.lineItems
          .map(
            (item) => `
          <tr>
            <td>${item.number}</td>
            <td>${item.payee}</td>
            <td>${item.description}</td>
            <td class="amount">${item.amount}</td>
          </tr>
        `
          )
          .join('')}
      </tbody>
    </table>
  </div>

  <div class="totals">
    <table class="totals-table">
      <tr>
        <td>Subtotal</td>
        <td class="amount">${content.totals.subtotal}</td>
      </tr>
      <tr class="total-row">
        <td>Total</td>
        <td class="amount">${content.totals.total}</td>
      </tr>
    </table>
  </div>

  ${
    content.signatures.length > 0
      ? `
  <div class="signatures">
    <h2>Signatures</h2>
    <div class="signature-grid">
      ${content.signatures
        .map(
          (sig) => `
        <div class="signature-block">
          <div class="signature-name">${sig.name}</div>
          <div class="signature-date">${sig.dateLabel}</div>
        </div>
      `
        )
        .join('')}
    </div>
  </div>
  `
      : ''
  }

  <div class="footer">
    ${content.footer.text} | Generated: ${new Date(content.footer.generatedAt).toLocaleString()}
  </div>
</body>
</html>
`.trim()
}

/**
 * Upload PDF to storage (placeholder)
 */
export async function uploadPdf(
  buffer: Buffer,
  filename: string,
  tenantSlug: string
): Promise<{ success: boolean; url?: string; error?: string }> {
  // Check for Vercel Blob storage
  const blobToken = process.env.BLOB_READ_WRITE_TOKEN

  if (blobToken) {
    try {
      const { put } = await import('@vercel/blob')
      const blob = await put(`tenants/${tenantSlug}/treasury/${filename}`, buffer, {
        access: 'public',
        contentType: 'application/pdf',
      })
      return { success: true, url: blob.url }
    } catch (error) {
      console.error('Blob upload error:', error)
    }
  }

  // Fallback: return base64 data URL (not recommended for production)
  const base64 = buffer.toString('base64')
  return {
    success: true,
    url: `data:application/pdf;base64,${base64}`,
  }
}

/**
 * Format currency amount
 */
function formatCurrency(cents: number, currency = 'USD'): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency,
  }).format(cents / 100)
}
