/**
 * @cgk/communications - Email Communications Package
 *
 * Provides email sender management, DNS configuration, domain verification,
 * notification routing, and email queue management.
 *
 * @ai-pattern communications
 * @ai-critical Never hardcode sender addresses - always use getSenderForNotification()
 */

// Types
export {
  DEFAULT_NOTIFICATION_ROUTING,
  NOTIFICATION_TYPES,
  type CreateDomainInput,
  type CreateSenderAddressInput,
  type DNSRecord,
  type DNSRecords,
  type EmailDomain,
  type NotificationChannel,
  type NotificationRouting,
  type NotificationRoutingWithSender,
  type NotificationType,
  type ResolvedSender,
  type SenderAddress,
  type SenderAddressWithDomain,
  type SenderPurpose,
  type SenderResolutionResult,
  type SendTestEmailInput,
  type SendTestEmailResult,
  type UpdateNotificationRoutingInput,
  type UpdateSenderAddressInput,
  type VerificationStatus,
} from './types.js'

// Sender module
export {
  // DNS instructions
  formatDNSRecordRow,
  formatDNSRecordsTable,
  generateDNSInstructions,
  getCommonRegistrars,
  getProviderInstructions,
  type DNSInstructions,
  type DNSInstructionStep,
  // Domain management
  createDomain,
  deleteDomain,
  domainExists,
  getDomainById,
  getDomainsByStatus,
  getFullDomainString,
  getVerifiedDomains,
  listDomains,
  updateDomainDNSRecords,
  updateDomainLastCheck,
  updateDomainVerificationStatus,
  // Sender address management
  createSenderAddress,
  deleteSenderAddress,
  emailAddressExists,
  formatSenderAddress,
  getDefaultSender,
  getDefaultSenderForPurpose,
  getSenderAddressById,
  getSenderAddressesByPurpose,
  getVerifiedSenderAddresses,
  listSenderAddresses,
  listSenderAddressesByDomain,
  updateSenderAddress,
  // Notification routing
  getAllNotificationRoutingStatus,
  getNotificationRouting,
  getSenderForNotification,
  listNotificationRouting,
  seedDefaultNotificationRouting,
  upsertNotificationRouting,
  // Domain verification
  canVerifyDomain,
  deleteDomainFromResend,
  getDomainStatusFromResend,
  getNextCheckAllowedAt,
  getResendConfig,
  registerDomainWithResend,
  verifyDomainWithResend,
  type VerificationResult,
} from './sender/index.js'

// Template module
export {
  // Types
  type CreateTemplateInput,
  type DefaultTemplate,
  type EmailTemplate,
  type EmailTemplateVersion,
  type NotificationType as TemplateNotificationType,
  type PreviewInput,
  type RenderOptions,
  type RenderedEmail,
  type TemplateCategory,
  type TemplateFilters,
  type TemplateVariable,
  type TestSendInput,
  type UpdateTemplateInput,
  type VariableType,
  // Variables
  COMMON_VARIABLES,
  NOTIFICATION_VARIABLES,
  getSampleDataForType,
  getVariablesForType,
  validateRequiredVariables,
  // Defaults
  DEFAULT_TEMPLATES,
  getAllDefaultTemplates,
  getDefaultTemplate,
  getDefaultTemplatesForType,
  // Database operations
  createTemplate,
  deleteTemplate,
  getTemplate,
  getTemplateById,
  getTemplateForTenant,
  getTemplates,
  getTemplateVersion,
  getTemplateVersions,
  resetToDefault,
  restoreVersion,
  seedDefaultTemplates,
  updateTemplate,
  // Rendering
  extractTemplateVariables,
  formatCurrency,
  formatDate,
  htmlToPlainText,
  previewTemplate,
  previewTemplateWithSampleData,
  renderEmailTemplate,
  substituteVariables,
  validateTemplateContent,
  // Library aggregation
  filterTemplatesByStatus,
  getTemplateAnalytics,
  getTemplateEditorPath,
  getTemplateLibrary,
  searchTemplates,
  type TemplateAnalyticsItem,
  type TemplateAnalyticsResponse,
  type TemplateLibraryCategory,
  type TemplateLibraryItem,
  type TemplateLibraryResponse,
  type TrendDataPoint,
} from './templates/index.js'

// Queue module
export {
  // Types
  type BaseQueueEntry,
  type BulkAction,
  type BulkActionResult,
  type CreateQueueEntryInput,
  type CreatorQueueEntry,
  type EsignQueueEntry,
  type QueueEntry,
  type QueueFilters,
  type QueueStats,
  type QueueStatus,
  type QueueType,
  type ReviewQueueEntry,
  type SendResult,
  type SubscriptionQueueEntry,
  type TeamInvitationQueueEntry,
  type TreasuryQueueEntry,
  type TriggerEvent,
  // Claim operations
  claimScheduledEntries,
  getEntriesByRunId,
  getEntryById,
  markAsFailed,
  markAsProcessing,
  markAsSent,
  markAsSkipped,
  resetStaleProcessingEntries,
  resetToScheduled,
  updateEntryStatus,
  // Sequence operations
  createFollowUpEntry,
  createReviewFollowUp,
  generateSequenceId,
  getEntriesForOrder,
  getLatestEntryForOrder,
  getSequenceEntries,
  getSentCountForOrder,
  hasAnyEntrySent,
  skipPendingEntriesForEmail,
  skipPendingEntriesForOrder,
  // Retry operations
  calculateRetryDelay,
  canRetry,
  getFailedEntriesByErrorType,
  getPermanentlyFailedEntries,
  getRetryableEntries,
  getTimeUntilRetry,
  isPermanentlyFailed,
  resetAndRetry,
  scheduleRetry,
  scheduleRetryBulk,
  // Statistics
  getAllQueueStats,
  getAverageSendTimes,
  getDailySendStats,
  getQueueEntries,
  getQueueStats,
  getQueueStatsForRange,
  getTemplateStats,
  getUpcomingScheduledCount,
  // Review queue operations
  createReviewQueueEntry,
  getEntriesAwaitingDelivery,
  getEntriesForCustomer,
  getPendingEntriesReadyToSchedule,
  getReviewStatsbyTemplate,
  hasReviewBeenSubmitted,
  onOrderDelivered,
  onOrderFulfilled,
  rescheduleEntry,
  updateIncentiveInfo,
  // Bulk operations
  archiveOldEntries,
  bulkRescheduleByDateRange,
  bulkRetryByFilter,
  bulkSkipByFilter,
  deleteOldEntries,
  getMatchingEntryIds,
  performBulkAction,
} from './queue/index.js'

// Processor module
export {
  // Base processor
  BaseEmailProcessor,
  createProcessor,
  type EntryProcessor,
  type ProcessorConfig,
  type ProcessorResult,
  // Review processor
  ReviewEmailProcessor,
  createReviewProcessor,
  createReviewProcessorJob,
  type ReviewProcessorConfig,
  // Retry processor
  RetryProcessor,
  createRetryProcessor,
  createRetryProcessorJob,
  type RetryProcessorConfig,
  type RetryProcessorResult,
} from './processors/index.js'

// Inbound email module
export {
  // Types
  type ApprovalConfidence,
  type ApprovalParseResult,
  type ApprovalStatus,
  type AutoResponseLog,
  type AutoResponseRule,
  type ConditionField,
  type ConditionOperator,
  type ContactInfo,
  type ContactType,
  type CreateAutoResponseRuleInput,
  type CreateThreadInput,
  type CreateThreadMessageInput,
  type CreateTreasuryCommunicationInput,
  type CreateTreasuryReceiptInput,
  type CreatorCommsSummary,
  type CreatorHandlerResult,
  type CreatorThreadInfo,
  type EmailAnalysisResult,
  type EmailThread,
  type InboundAddressInfo,
  type InboundAddressPurpose,
  type InboundAttachment,
  type InboundEmail,
  type InboundEmailFilters,
  type InboundEmailLog,
  type InboundEmailType,
  type InboundProcessingResult,
  type InboundProcessingStatus,
  type LogInboundEmailInput,
  type MatchedThread,
  type ProcessedReceipt,
  type ReceiptFilters,
  type ReceiptHandlerResult,
  type ReceiptStatus,
  type RuleCondition,
  type StoredAttachment,
  type SupportHandlerResult,
  type ThreadFilters,
  type ThreadMessage,
  type ThreadStatus,
  type TreasuryCommunication,
  type TreasuryHandlerResult,
  type TreasuryReceipt,
  type UpdateTreasuryReceiptInput,
  type UploadToBlobFn,
  // Webhook handler
  findInboundAddressByEmail,
  getInboundEmailById,
  listInboundEmails,
  logInboundEmail,
  logUnknownInbound,
  parseInboundEmail,
  updateInboundLogStatus,
  verifyResendSignature,
  verifySvixSignature,
  // Treasury parser
  APPROVAL_KEYWORDS,
  AUTO_REPLY_PATTERNS,
  extractTreasuryRequestId,
  getParseResultSummary,
  isAutoReply,
  isValidTreasuryRequestId,
  parseTreasuryApproval,
  // Auto-reply detector
  AUTO_REPLY_BODY_PATTERNS,
  AUTO_REPLY_HEADER_VALUES,
  AUTO_REPLY_SUBJECT_PREFIXES,
  AUTOMATED_PRECEDENCE_VALUES,
  analyzeEmail,
  calculateSpamScore,
  detectAutoReply,
  hasAutoReplyBody,
  isAutoReplySubject,
  isLikelySpam,
  isNoReplySender,
  SPAM_PATTERNS,
  SUSPICIOUS_SENDER_PATTERNS,
  // Receipt processor
  defaultUploadToBlob,
  extractAmountFromText,
  extractDateFromText,
  extractReceiptData,
  extractVendorFromText,
  filterReceiptAttachments,
  generateReceiptBlobPath,
  isReceiptAttachment,
  isValidAttachmentSize,
  MAX_ATTACHMENT_SIZE,
  processReceiptEmail,
  RECEIPT_CONTENT_TYPES,
  // Thread matcher
  addInboundToThread,
  addMessageToThread,
  createThread,
  findContactByEmail,
  findCreatorByEmail,
  findCustomerByEmail,
  findMessageByMessageId,
  findOpenThreadForContact,
  findThreadByEmail,
  matchToThread,
  updateThreadStats,
  // Creator replies
  findOrCreateCreatorThread,
  getCreatorCommsSummary,
  getCreatorThreads,
  getThreadMessages,
  handleCreatorReply,
  // Router
  createTreasuryCommunication,
  createTreasuryReceipt,
  getEmailTypeFromPurpose,
  handleCreatorReplyEmail,
  handleGenericEmail,
  handleReceiptEmail,
  handleSupportEmail,
  handleTreasuryEmail,
  routeEmail,
} from './inbound/index.js'

// Onboarding module
export {
  // Types
  type AddDomainInput,
  type CompleteEmailSetupInput,
  type CompleteEmailSetupResult,
  type ConfigureInboundInput,
  type ConfigureRoutingInput,
  type CreateSenderInput,
  type DomainConfigStatus,
  type EmailOnboardingState,
  type EmailOnboardingSubStep,
  type EmailSetupStatus,
  type InboundAddressConfig,
  type InboundRecommendation,
  type InboundWebhookInfo,
  type NotificationRoutingConfig,
  type NotificationTypeInfo,
  type OnboardingStepStatus,
  type RecommendedSenderAddress,
  type RecommendedSubdomain,
  type ResendApiKeyInfo,
  type TestEmailInput,
  type TestEmailResult,
  type VerifyApiKeyInput,
  type VerifyApiKeyResult,
  RECOMMENDED_SENDER_ADDRESSES,
  RECOMMENDED_SUBDOMAINS,
  // API Key Verification
  checkApiKeyPermissions,
  sendTestEmailWithKey,
  verifyResendApiKey,
  // Domain Setup
  addOnboardingDomain,
  getDomainDNSInstructions,
  getDomainsWithStatus,
  getPrimaryDomain,
  getRecommendedSubdomains,
  getVerifiedDomainCount,
  hasVerifiedDomain,
  isValidDomain,
  isValidSubdomain,
  verifyOnboardingDomain,
  // Sender Address Setup
  createOnboardingSenderAddress,
  getRecommendedSenders,
  getSenderAddressCount,
  getSendersByPurpose,
  getVerifiedSenderCount,
  hasMinimumSenders,
  hasSenderForPurpose,
  sendTestEmail,
  // Inbound Email Setup
  configureInboundAddresses,
  createInboundTestInstructions,
  getInboundCapableAddresses,
  getInboundEnabledCount,
  getInboundRecommendations,
  getInboundWebhookUrl,
  hasInboundEnabled,
  // Notification Routing Setup
  autoAssignSenderAddresses,
  configureNotificationRouting,
  getNotificationTypesByCategory,
  getNotificationTypesInfo,
  getRoutingStatus,
  initializeNotificationRouting,
  setAllInCategoryEnabled,
  // Completion
  canSendEmails,
  completeEmailSetup,
  getEmailSetupStatus,
  getOnboardingState,
  isEmailSetupComplete,
  resetEmailSetup,
} from './onboarding/index.js'

// SMS module (Optional Channel - OFF by default)
export {
  // Types
  SMS_COMMON_VARIABLES,
  SMS_NOTIFICATION_TYPES,
  type ComplianceCheckResult,
  type ComplianceSkipReason,
  type CreateSmsOptOutInput,
  type CreateSmsQueueEntryInput,
  type CreateSmsTemplateInput,
  type NotificationChannelSettings,
  type SmsHealthStatus,
  type SmsNotificationType,
  type SmsOptOut,
  type SmsOptOutMethod,
  type SmsProcessorConfig,
  type SmsProcessorResult,
  type SmsProvider,
  type SmsQueueEntry,
  type SmsQueueFilters,
  type SmsQueueStats,
  type SmsQueueStatus,
  type SmsRecipientType,
  type SmsSendRequest,
  type SmsSendResult,
  type SmsSetupStatus,
  type SmsSetupStep,
  type SmsTemplate,
  type SmsVariable,
  type TenantSmsSettings,
  type TestSmsRequest,
  type TestSmsResult,
  type TwilioIncomingMessage,
  type TwilioMessageStatus,
  type TwilioVerificationResult,
  type UpdateNotificationChannelSettingsInput,
  type UpdateSmsSettingsInput,
  type UpdateSmsTemplateInput,
  type WebhookResult,
  // Settings management
  getSmsEnabledTenants,
  getSmsSettings,
  getTwilioCredentials,
  hasValidTwilioConfig,
  isSmsEnabled,
  markSmsSetupCompleted,
  updateSmsHealthStatus,
  updateSmsSettings,
  // Twilio provider
  generateEmptyTwimlResponse,
  getTwilioPhoneNumber,
  isDeliveredStatus,
  isFailedStatus,
  parseTwilioIncomingMessage,
  parseTwilioStatusWebhook,
  sendSms,
  sendTestSms,
  verifyTwilioCredentials,
  // Compliance (TCPA)
  OPT_IN_KEYWORDS,
  OPT_OUT_KEYWORDS,
  calculateSegmentCount,
  exceedsSingleSegment,
  getNextAllowedSendTime,
  getQuietHoursRemainingMinutes,
  getRecommendedMaxLength,
  isOptInMessage,
  isOptOutMessage,
  isQuietHours,
  isValidE164PhoneNumber,
  maskPhoneNumber,
  normalizeToE164,
  performComplianceChecks,
  // Opt-out management
  addOptOut,
  checkBulkOptOutStatus,
  findTenantByTwilioNumber,
  getOptOut,
  getOptOutStats,
  handleStartKeyword,
  handleStopKeyword,
  isOptedOut,
  listOptOuts,
  removeOptOut,
  // Queue operations
  claimScheduledSmsEntries,
  createSmsQueueEntry,
  getDailySmsCount,
  getRetryableSmsEntries,
  getSmsQueueEntry,
  getSmsQueueEntryByMessageSid,
  getSmsQueueStats,
  isDailyLimitExceeded,
  listSmsQueueEntries,
  markSmsDelivered,
  markSmsFailed,
  markSmsSent,
  markSmsSkipped,
  resetStaleSmSProcessingEntries,
  scheduleEntry as scheduleSmsEntry,
  scheduleRetry as scheduleSmsRetry,
  // Template management
  createSmsTemplate,
  DEFAULT_SMS_TEMPLATES,
  deleteSmsTemplate,
  extractVariables as extractSmsVariables,
  getOrCreateDefaultTemplate as getOrCreateDefaultSmsTemplate,
  getSmsTemplateById,
  getSmsTemplateByType,
  listSmsTemplates,
  previewTemplate as previewSmsTemplate,
  renderSmsTemplate,
  SAMPLE_DATA as SMS_SAMPLE_DATA,
  seedDefaultSmsTemplates,
  substituteVariables as substituteSmsVariables,
  updateSmsTemplate,
  validateVariables as validateSmsVariables,
  // Queue processor
  aggregateResults as aggregateSmsResults,
  createSmsProcessorJob,
  createSmsRetryProcessorJob,
  formatProcessorResult as formatSmsProcessorResult,
  processAllTenantsSmsQueue,
  processTenantSmsQueue,
  // Webhook handlers
  createJsonResponse,
  createTwimlResponse,
  handleIncomingSmsWebhook,
  handleStatusWebhook,
  parseFormData,
  verifyTwilioSignature,
} from './sms/index.js'
