-- Blog clusters for topic clustering (pillar-spoke SEO strategy)
-- Phase 2I: Advanced Blog Features

-- Create blog clusters table
CREATE TABLE IF NOT EXISTS blog_clusters (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,

  -- Cluster identification
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,

  -- SEO targeting
  target_keywords TEXT[] DEFAULT '{}',

  -- Visual identification (8 color options)
  color TEXT NOT NULL DEFAULT 'blue' CHECK (color IN ('blue', 'green', 'red', 'yellow', 'purple', 'pink', 'orange', 'teal')),

  -- Pillar post (main comprehensive post for the cluster)
  pillar_post_id TEXT REFERENCES blog_posts(id) ON DELETE SET NULL,

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Junction table for posts in clusters
CREATE TABLE IF NOT EXISTS blog_post_clusters (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,

  post_id TEXT NOT NULL REFERENCES blog_posts(id) ON DELETE CASCADE,
  cluster_id TEXT NOT NULL REFERENCES blog_clusters(id) ON DELETE CASCADE,

  -- Role in cluster: 'pillar' or 'spoke'
  role TEXT NOT NULL DEFAULT 'spoke' CHECK (role IN ('pillar', 'spoke')),

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE(post_id, cluster_id)
);

-- Link health cache table for periodic analysis results
CREATE TABLE IF NOT EXISTS blog_link_health_cache (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,

  -- Overall health metrics
  total_posts INTEGER NOT NULL DEFAULT 0,
  orphaned_posts INTEGER NOT NULL DEFAULT 0,
  one_way_links INTEGER NOT NULL DEFAULT 0,
  posts_without_products INTEGER NOT NULL DEFAULT 0,
  low_authority_posts INTEGER NOT NULL DEFAULT 0,

  -- Health score (0-100)
  health_score INTEGER NOT NULL DEFAULT 0,

  -- Detailed issues as JSON array
  issues JSONB NOT NULL DEFAULT '[]',

  -- Analysis metadata
  analyzed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- AI content tracking columns for blog_posts
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS ai_source TEXT CHECK (ai_source IN ('MCP', 'ChatGPT', 'Claude', 'Other'));
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS original_content TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS human_edit_percentage DECIMAL(5,2);
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS ai_tracking_calculated_at TIMESTAMPTZ;

-- Quality score cache columns for blog_posts
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS quality_score INTEGER;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS quality_breakdown JSONB;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS quality_calculated_at TIMESTAMPTZ;

-- Author credential fields for E-E-A-T (only if blog_authors exists)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = 'blog_authors') THEN
    EXECUTE 'ALTER TABLE blog_authors ADD COLUMN IF NOT EXISTS credentials TEXT[]';
    EXECUTE 'ALTER TABLE blog_authors ADD COLUMN IF NOT EXISTS expertise_areas TEXT[]';
    EXECUTE 'ALTER TABLE blog_authors ADD COLUMN IF NOT EXISTS is_team_account BOOLEAN NOT NULL DEFAULT FALSE';
  END IF;
END $$;

-- Indexes for efficient queries
CREATE INDEX IF NOT EXISTS idx_blog_clusters_slug ON blog_clusters(slug);
CREATE INDEX IF NOT EXISTS idx_blog_post_clusters_post_id ON blog_post_clusters(post_id);
CREATE INDEX IF NOT EXISTS idx_blog_post_clusters_cluster_id ON blog_post_clusters(cluster_id);
CREATE INDEX IF NOT EXISTS idx_blog_post_clusters_role ON blog_post_clusters(role);
CREATE INDEX IF NOT EXISTS idx_blog_posts_ai_generated ON blog_posts(is_ai_generated);
CREATE INDEX IF NOT EXISTS idx_blog_posts_quality_score ON blog_posts(quality_score);

-- Trigger for updated_at on clusters
DROP TRIGGER IF EXISTS update_blog_clusters_updated_at ON blog_clusters;
CREATE TRIGGER update_blog_clusters_updated_at
  BEFORE UPDATE ON blog_clusters
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Trigger for updated_at on link health cache
DROP TRIGGER IF EXISTS update_blog_link_health_cache_updated_at ON blog_link_health_cache;
CREATE TRIGGER update_blog_link_health_cache_updated_at
  BEFORE UPDATE ON blog_link_health_cache
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

COMMENT ON TABLE blog_clusters IS 'Topic clusters for pillar-spoke SEO strategy';
COMMENT ON TABLE blog_post_clusters IS 'Junction table linking posts to clusters';
COMMENT ON TABLE blog_link_health_cache IS 'Cached results of link health analysis';
COMMENT ON COLUMN blog_posts.is_ai_generated IS 'Whether the content was generated by AI';
COMMENT ON COLUMN blog_posts.ai_source IS 'Source of AI-generated content';
COMMENT ON COLUMN blog_posts.original_content IS 'Original AI-generated content for diff comparison';
COMMENT ON COLUMN blog_posts.human_edit_percentage IS 'Percentage of content edited by humans (0-100)';
COMMENT ON COLUMN blog_posts.quality_score IS 'Cached quality score (0-100)';
COMMENT ON COLUMN blog_posts.quality_breakdown IS 'Cached breakdown by category (SEO, readability, E-E-A-T, formatting)';
